# Generated by Django 5.1.3 on 2024-12-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tags',
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Web Solutions', 'Web Solutions'), ('Custom Development', 'Custom Development'), ('System Architecture', 'System Architecture')], default='Web Solutions', max_length=50),
        ),
    ]
